FROM ubuntu

RUN apt-get update && apt-get install -y bind9

COPY named.conf /etc/bind/
COPY named.conf.local /etc/bind/
COPY db.balance.com /etc/bind/
COPY named.conf.options /etc/bind/
COPY db.192.168.56 /etc/bind/

RUN chown -R bind:bind /etc/bind/

EXPOSE 53/udp
EXPOSE 53/tcp

WORKDIR /etc/bind

CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf"]
